In [22]:
import glob
import pandas as pd
import os
train_df = pd.DataFrame()
for dn in glob.glob("chinese_news_trans/*"):
    basedn = os.path.basename(dn)
    for fn in glob.glob(dn + "/*.txt"):
        with open(fn, "r", encoding="utf-8") as f:
            news = f.read()
       
        row = {"content":news, "category":basedn}               
        train_df = train_df.append(row, ignore_index=True)
train_df

     category                                            content
0          交通  【 日  期 】19960104\n【 版  號 】1\n【 標  題 】合巢蕪高速公路巢蕪...
1          交通  【 日  期 】19960226\n【 版  號 】5\n【 標  題 】我首臺載人磁懸浮列...
2          交通             大秦鐵路萬噸列車試運成功\n新華社北京５月２４日電（通訊員李忠民）大秦...
3          交通             遼寧省檯安縣村村都通柏油路鄉村公路建設全國數第\n一\n    (4)...
4          交通             北京—烏蘭巴托—莫斯料３／４次國際旅客列車通車\n３０週年\n    ...
...       ...                                                ...
2632       體育             馬玉芹破女子４００米跑全國青年紀錄\n新華社鞍山５月１０日電（通訊員王...
2633       體育             國際奧委會中國臺北委員吳經國訪問北京\n新華社北京５月１０日電記者《中...
2634       體育             亞奧理事會３９個成員組織全部以書面形式確認參加\n第十一屆亞運會\n ...
2635       體育             世界盃乒乓球團體賽男子團體採用新賽制\n新華社北京５月１０日電（記者樑...
2636       體育             登頂隊員簡介\n新華社珠穆朗瑪峰５月１０日電登頂隊員簡介\n     ...

[2637 rows x 2 columns]

In [23]:
test_df = pd.DataFrame()
for dn in glob.glob("chinese_news_test/*"):
    basesn = os.path.basename(sn)
    for fn in glob.glob(sn + "/*.txt"):
        with open(fn, "r", encoding="utf-8") as f:
            news = f.read()
        
        row = {"content":news, "category":basesn}               
        test_df = test_df.append(row, ignore_index=True)
test_df

    category                                            content
0         體育  不解之謎\n\n　　第2屆奧運會在法國巴黎舉行。這次奧運會的馬拉松比賽的赳點和終點均設在當作...
1         體育  　　亞運會游泳賽中國臺北隊改寫歷史\n\n\n　　\n　　新華社曼谷１２月８日電（記者樹文、...
2         體育  我軍選手備戰國際軍體第二十八屆世界柔道錦標賽紀事\n\n　　●本報記者　許沛成 \n\n　　...
3         體育  中國青島－韓國大邱健美表演賽和對抗賽將舉辦\n \n　 \n    應青島市體育總會、青島市...
4         體育  男子健美初登亞運會 中國猛男直指前三\n \n　 \n    在即將開幕的釜山亞運會上，男子...
..       ...                                                ...
105       體育  最優秀選手無緣亞運會健美賽\n \n　 \n    健美在亞洲運動會上是“新生兒”——韓國釜...
106       體育   \n各國記者眼中的羽毛球世錦賽\n \n\n-----------------------...
107       體育  \n友好運動會第五天 東道主選手大顯神威\n2001年09月03日02:51:40 新華社 ...
108       體育  不靠技術比運氣\n\n　　第二屆奧運會在巴黎舉行，同時這裡也正在舉行國際博覽會，東道主把一些...
109       體育  帆 板 運 動 簡 介（二）\n\n　　我國在79年由國家體委青島航海運動學校成功試製出第一...

[110 rows x 2 columns]

In [21]:
cat = train_df["category"].unique()
trans = {v:i for i, v in enumerate(cat)}
y_train = train_df["category"].replace(trans)
y_test = test_df["category"].replace(trans)
y_test

0      0
1      0
2      0
3      0
4      0
      ..
96     9
97     9
98     9
99     9
100    9
Name: category, Length: 101, dtype: int64

In [ ]:
from jieba import cut, set_dictionary
from urllib.request import urlretrieve
import os
os.path.exists("dict.txt.big"):
    print("幫下載大辭典")
    url = 
    urlretrieve(url,)
#Series.apply(func)
def newscut(s):
    s=(s.replace("\r"," ")
   .replace("\n"," ")
   .replace("，"," ")
   .replace("。"," "))

    return" ".join(cut(s)) 
x_train = train_df["content"].apply(poemcut)
x_test = test_df["content"].apply(poemcut)
x_test

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
x_train_vec = vec.fit_transform(x_train)